export type Country = { name: string; dial: string }

export const COUNTRIES: Country[] = [
  { name: "United States", dial: "+1" },
  { name: "Canada", dial: "+1" },
  { name: "United Kingdom", dial: "+44" },
  { name: "Ireland", dial: "+353" },
  { name: "Germany", dial: "+49" },
  { name: "France", dial: "+33" },
  { name: "Netherlands", dial: "+31" },
  { name: "Belgium", dial: "+32" },
  { name: "Luxembourg", dial: "+352" },
  { name: "Switzerland", dial: "+41" },
  { name: "Austria", dial: "+43" },
  { name: "Spain", dial: "+34" },
  { name: "Portugal", dial: "+351" },
  { name: "Italy", dial: "+39" },
  { name: "Greece", dial: "+30" },
  { name: "Poland", dial: "+48" },
  { name: "Czech Republic", dial: "+420" },
  { name: "Slovakia", dial: "+421" },
  { name: "Hungary", dial: "+36" },
  { name: "Romania", dial: "+40" },
  { name: "Bulgaria", dial: "+359" },
  { name: "Croatia", dial: "+385" },
  { name: "Slovenia", dial: "+386" },
  { name: "Serbia", dial: "+381" },
  { name: "Denmark", dial: "+45" },
  { name: "Sweden", dial: "+46" },
  { name: "Norway", dial: "+47" },
  { name: "Finland", dial: "+358" },
  { name: "Iceland", dial: "+354" },
  { name: "Estonia", dial: "+372" },
  { name: "Latvia", dial: "+371" },
  { name: "Lithuania", dial: "+370" },
  { name: "Ukraine", dial: "+380" },
  { name: "Turkey", dial: "+90" },
  { name: "Russia", dial: "+7" },
  { name: "Australia", dial: "+61" },
  { name: "New Zealand", dial: "+64" },
  { name: "Japan", dial: "+81" },
  { name: "South Korea", dial: "+82" },
  { name: "China", dial: "+86" },
  { name: "Hong Kong", dial: "+852" },
  { name: "Taiwan", dial: "+886" },
  { name: "Singapore", dial: "+65" },
  { name: "Malaysia", dial: "+60" },
  { name: "Indonesia", dial: "+62" },
  { name: "Thailand", dial: "+66" },
  { name: "Vietnam", dial: "+84" },
  { name: "Philippines", dial: "+63" },
  { name: "India", dial: "+91" },
  { name: "Pakistan", dial: "+92" },
  { name: "Bangladesh", dial: "+880" },
  { name: "Sri Lanka", dial: "+94" },
  { name: "Nepal", dial: "+977" },
  { name: "United Arab Emirates", dial: "+971" },
  { name: "Saudi Arabia", dial: "+966" },
  { name: "Qatar", dial: "+974" },
  { name: "Kuwait", dial: "+965" },
  { name: "Bahrain", dial: "+973" },
  { name: "Oman", dial: "+968" },
  { name: "Israel", dial: "+972" },
  { name: "Jordan", dial: "+962" },
  { name: "Lebanon", dial: "+961" },
  { name: "Egypt", dial: "+20" },
  { name: "South Africa", dial: "+27" },
  { name: "Nigeria", dial: "+234" },
  { name: "Kenya", dial: "+254" },
  { name: "Ghana", dial: "+233" },
  { name: "Morocco", dial: "+212" },
  { name: "Ethiopia", dial: "+251" },
  { name: "Tanzania", dial: "+255" },
  { name: "Uganda", dial: "+256" },
  { name: "Brazil", dial: "+55" },
  { name: "Mexico", dial: "+52" },
  { name: "Argentina", dial: "+54" },
  { name: "Chile", dial: "+56" },
  { name: "Colombia", dial: "+57" },
  { name: "Peru", dial: "+51" },
  { name: "Uruguay", dial: "+598" },
  { name: "Ecuador", dial: "+593" },
  { name: "Panama", dial: "+507" },
  { name: "Costa Rica", dial: "+506" },
  { name: "Dominican Republic", dial: "+1" },
  { name: "Jamaica", dial: "+1" },
  { name: "Trinidad and Tobago", dial: "+1" },
]

export const COUNTRY_NAMES: string[] = COUNTRIES.map((c) => c.name).sort(
  (a, b) => a.localeCompare(b)
)
