export const BG = '#000000'
export const TEXT_PRIMARY = '#FFFFFF'
export const TEXT_SECONDARY = '#8A8F98'
export const CRITICAL = '#FF2A2A'
export const INACTIVE_SEGMENT = '#2E2E2E'
export const HAIRLINE = '#1C1C1C'
