"""widen float columns to double

Hand-written, not autogenerated. Autogenerate ran against a database standing at base
and proposed recreating every table; and duckdb-engine's reflection does not report a
FLOAT/DOUBLE difference as a type change, so it would not have produced these alters
even against an upgraded database.

SQLAlchemy maps a bare `Mapped[float]` to a 4-byte FLOAT. Every float in the `app` schema
is a threshold, a weight or a similarity score that a person set and expects to read back
unchanged, and at single precision 0.8 comes back as 0.800000011920929 — a number nobody
typed, displayed next to the one they did. `Base.type_annotation_map` now maps float to
Double so no new column can inherit the old default; this migration brings the three
existing columns into line.

Revision ID: fb392736a7a7
Revises: a9a061850aad
Create Date: 2026-08-19
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fb392736a7a7"
down_revision: str | None = "a9a061850aad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "app"

# (table, column, nullable)
FLOAT_COLUMNS: tuple[tuple[str, str, bool], ...] = (
    ("resolution_weight_overrides", "weight", False),
    ("ground_truth_labels", "score_at_labelling", True),
    ("detection_rule_overrides", "threshold", True),
)


def upgrade() -> None:
    for table, column, nullable in FLOAT_COLUMNS:
        op.alter_column(
            table,
            column,
            type_=sa.Double(),
            existing_type=sa.Float(),
            existing_nullable=nullable,
            schema=SCHEMA,
        )


def downgrade() -> None:
    """Lossy by nature, and that is the honest direction.

    Narrowing DOUBLE back to FLOAT discards precision that cannot be recovered. It is
    written out anyway so the round-trip test can run — a migration that cannot be
    reversed is a migration that cannot be rolled back.
    """
    for table, column, nullable in FLOAT_COLUMNS:
        op.alter_column(
            table,
            column,
            type_=sa.Float(),
            existing_type=sa.Double(),
            existing_nullable=nullable,
            schema=SCHEMA,
        )
